IDs:
  controls:
    comparators: estimatesComparator
    populations: estimatesPopulation
    ages: estimatesAges
    outcomes: estimatesOutcomes
    interventions: estimatesInterventions
    analyses: estimatesAnalyses
    labels: estimatesLabels
    colorblind: estimatesColorblind
  downloads:
    png: estimatesPNG
    pdf: estimatesPDF
    pptx: estimatesPPTX
    csv: estimatesCSV
    xlsx: esimtatesXLSX
  panels:
    control: estimatesControlPanel
    visualization: estimatesVisualizationPanel
  brush: estimatesPlotBrush
  click: esimtatesPlotClick
  dblclick: estimatesPlotDblclick
  title: estimatesTitle
  subtitle: estimatesSubtitle
  plot: estimatesPlot
comparators:
  heading: Comparison
  values:
  - absolute_value
  - pct_basecase_same_year
  - pct_basecase_2018
  labels:
    absolute_value: Absolute values
    pct_basecase_same_year: Percentage of base case value in the same year
    pct_basecase_2018: Percentage of base case value in 2018
  formatted:
    absolute_value: ''
    pct_basecase_same_year: Percentage of base case value in the same year
    pct_basecase_2018: Percentage of base case value in 2018
  selected:
  - yes
  - no
  - no
populations:
  heading: Population
  values:
  - all_populations
  - usb_population
  - fb_population
  labels:
    all_populations: Total
    usb_population: US-born
    fb_population: Non-US-born
  formatted:
    all_populations: total population
    usb_population: US-born population
    fb_population: non-US-born population
  selected:
  - yes
  - no
  - no
ages:
  heading: Age groups
  values:
  - all_ages
  - age_0_24
  - age_25_64
  - age_65p
  labels:
    all_ages: All ages
    age_0_24: 0 to 24
    age_25_64: 25 to 64
    age_65p: 65+
  formatted:
    all_ages: all age groups
    age_0_24: 0 to 24 years old
    age_25_64: 25 to 64 years old
    age_65p: 65+ years old
  selected:
  - yes
  - no
  - no
  - no
outcomes:
  heading: Outcome
  values:
  - tb_infection_per_100k
  - pct_ltbi
  - tb_incidence_per_100k
  - tb_deaths_per_100k
  labels:
    tb_infection_per_100k: Incident M. tb Infections
    pct_ltbi: LTBI Prevalence
    tb_incidence_per_100k: Active TB Incidence
    tb_deaths_per_100k: TB-Related Deaths
  formatted:
    tb_infection_per_100k: |-
      Incident M. tb Infections
      (per 100,000)
    pct_ltbi: |-
      LTBI Prevalence
      (percentage)
    tb_incidence_per_100k: |-
      Active TB Incidence
      (per 100,000)
    tb_deaths_per_100k: |-
      TB-Related Deaths
      (per 100,000)
  descriptions:
    tb_infection_per_100k: Incident M. TB infections each year due to transmission
      within the US (includes reinfection of individuals with prior infection, excludes
      migrants entering the US with established LTBI)
    pct_ltbi: Prevalence of latent M. TB infections at mid-point of year
    tb_incidence_per_100k: TB cases identified each year (includes TB cases identified
      after death)
    tb_deaths_per_100k: Number of deaths attributable to TB each year
  selected:
  - yes
  - no
  - no
  - no
  abbreviations:
    tb_infection_per_100k: new-tb
    pct_ltbi: ltbi-prev
    tb_incidence_per_100k: tb-in
    tb_deaths_per_100k: tb-mort
interventions:
  heading: Modeled Scenarios
  values:
  - intervention_1
  - intervention_2
  - intervention_3
  - intervention_4
  - intervention_5
  labels:
    intervention_1: TLTBI for New Immigrants
    intervention_2: Improved TLTBI in the US
    intervention_3: Better Case Detection
    intervention_4: Better TB Treatment
    intervention_5: All Improvements
  descriptions:
    intervention_1: Provision of LTBI testing and treatment for all new legal
      immigrants entering the US
    intervention_2: Intensification of the current LTBI targeted testing and
      treatment policy for high-risk populations, doubling treatment uptake within
      each risk group compared to current levels, and increasing the fraction cured among
      individuals initiating LTBI treatment, via a 3-month Isoniazid-Rifapentine drug regimen
    intervention_3: Improved detection of active TB cases, such that the duration
      of untreated active disease (time from TB incidence to the initiation of
      treatment) is reduced by 50%
    intervention_4: Improved treatment quality for active TB, such that treatment default, failure
      rates, and the fraction of individuals receiving an incorrect drug regimen are
      reduced by 50% from current levels
    intervention_5: The combination of all intervention scenarios described above
analyses:
  heading: Sensitivity Analyses
  values:
  - scenario_1
  - scenario_2
  - scenario_3
  - scenario_5
  - scenario_6
  - scenario_7
  labels:
    scenario_1: No Transmission Within the US After 2018
    scenario_2: No TB or LTBI in New Migrants After 2018
    scenario_3: Reduced TB Prevention Effort
    scenario_5: Future Immigration at 2018 Levels
    scenario_6: Improving Global TB Control
    scenario_7: Rising Reactivation Risks
  formatted:
    scenario_1: |-
      No transmission within
      the US after 2018
    scenario_2: |-
      No TB or LTBI in new
      migrants after 2018
    scenario_3: |-
      Reduced TB prevention
      effort
    scenario_5: |-
      Future immigration at
      2018 levels
    scenario_6: |-
      Improving global TB
      control
    scenario_7: |-
      Rising reactivation
      risks
  descriptions:
    scenario_1: From 2018 onwards, no individuals acquire M. TB infection from transmission within
      the United States. In this scenario the only source of new LTBI cases is from
      existing infection in new immigrants.
    scenario_2: From 2018 onwards, all individuals immigrating to the United States are free of
      M. TB infection, while maintaining the same total volume of immigration.
labels:
  heading: Labels
  values:
  - none
  - means
  - intervals
  - all
  labels:
    None: none
    Mean values: means
    Confidence intervals: intervals
    All: all
downloads:
  heading: Download
  labels:
  - PNG
  - PDF
  - PPTX
  - CSV
  - XLSX
