IDs:
  controls:
    costs: costcomparisonCosts
    perspectives: costcomparisonPerspectives
    discount: costcomparisonDiscount
    interventions: costcomparisonInterventions
    analyses: costcomparisonAnalyses
    colorblind: costcomparisonColorblind
  downloads:
    png: costcomparisonPNG
    pdf: costcomparisonPDF
    pptx: costcomparisonPPTX
    csv: costcomparisonCSV
    xlsx: costcomparisonXLSX
  panels:
    control: costcomparisonControlPanel
    visualization: costcomparisonVisualizationPanel
  title: costcomparisonTitle
  subtitle: costcomparisonSubtitle
  plot: costcomparisonPlot
costs:
  heading: Effectiveness Measure
  values:
    - ltbi_tests_000s
    - ltbi_txinits_000s
    - ltbi_txcomps_000s
    - tb_txinits_000s 
  labels:
    ltbi_tests_000s: TB cases averted
    ltbi_txtests_000s: TB deaths averted
    ltbi_txcomps_000s: QALYs saved
    tb_txinits_000s: Life years saved
  formatted:
    ltbi_tests_000s: |-
      TB cases averted
    ltbi_txtests_000s: |-
      TB deaths averted
    ltbi_txcomps_000s: |-
      QALYs saved
    tb_txinits_000s: |-
       Life years saved
  descriptions:
       ltbi_tests_000s: TB cases averted
       ltbi_txtests_000s: TB deaths averted
       ltbi_txcomps_000s: QALYS saved
       tb_txinits_000s: Life years saved
  selected:
  - no
  - yes
  - no
  - no
perspectives:
  heading: Costing Perspective
  values:
    - ltbi_tests_000s
    - ltbi_txinits_000s
  labels:
    ltbi_tests_000s: Health services costs only
    ltbi_txtests_000s: Health services and patient productivity costs
  formatted:
    ltbi_tests_000s: |-
      Health System Costs Only
    ltbi_txtests_000s: |-
      Health System and Patient Productivity Costs
  descriptions:
       ltbi_tests_000s: Health System Costs Only
       ltbi_txtests_000s: Health System and Patient Productivity Costs
  selected:
  - no
  - yes
discount:
  heading: Discount health and economic outcomes??
  values:
    - ltbi_tests_000s
    - ltbi_txinits_000s
  labels:
    ltbi_tests_000s: Include
    ltbi_txtests_000s: Do not include
  formatted:
    ltbi_tests_000s: |-
      Include
    ltbi_txtests_000s: |-
      Do not include
  descriptions:
       ltbi_tests_000s: Include discount rate
       ltbi_txtests_000s: Do not include discount rate
  selected:
  - no
  - yes
interventions:
  heading: Modeled Scenarios
  values:
  - intervention_1
  - intervention_2
  - intervention_3
  - intervention_4
  - intervention_5
  labels:
    intervention_1: LTBI treatment for new migrants
    intervention_2: Improved LTBI treatment in the US
    intervention_3: Enhanced case detection
    intervention_4: Enhanced TB treatment
    intervention_5: All improvements
  descriptions:
    intervention_1: Provision of LTBI testing and treatment for all new legal
      immigrants entering the US
    intervention_2: Intensification of the current LTBI targeted testing and
      treatment policy for high-risk populations, doubling treatment uptake within
      each risk group compared to current levels, and increasing the fraction cured
      among individuals initiating LTBI treatment, via a 3-month Isoniazid-Rifapentine
      drug regimen
    intervention_3: Improved detection of TB cases, such that the duration
      of untreated disease (time from TB incidence to the initiation of
      treatment) is reduced by 50%
    intervention_4: Improved treatment quality for TB, such that treatment default,
      failure rates, and the fraction of individuals receiving an incorrect drug
      regimen are reduced by 50% from current levels
    intervention_5: The combination of all intervention scenarios described above
analyses:
  heading: Sensitivity Analyses
  values:
  - scenario_1
  - scenario_2
  - scenario_3
  - scenario_5
  - scenario_6
  - scenario_7
  labels:
    scenario_1: No Transmission Within the US After 2020
    scenario_2: No TB or LTBI in New Migrants After 2020
    scenario_3: Reduced TB Prevention Effort
    scenario_5: Future Immigration at 2020 Levels
    scenario_6: Improving Global TB Control
    scenario_7: Rising Reactivation Risks
  formatted: # the |- allows newlines
    scenario_1: |-
      No transmission within
      the US after 2020
    scenario_2: |-
      No TB or LTBI in new
      migrants after 2020
    scenario_3: |-
      Reduced TB prevention
      effort
    scenario_4: |-
      Rising MDR-TB in
      new migrants
    scenario_5: |-
      Future immigration at
      2020 levels
    scenario_6: |-
      Improving global TB
      control
    scenario_7: |-
      Rising reactivation
      risk
  descriptions:
    scenario_1: From 2020 onwards, no individuals acquire M. TB infection from transmission within
      the United States. In this scenario the only source of new LTBI cases is from
      existing infection in new immigrants.
    scenario_2: From 2020 onwards, all individuals immigrating to the United States are free of
      M. TB infection, while maintaining the same total volume of immigration.
downloads:
  heading: Download
  labels:
  - PNG
  - PDF
  - PPTX
  - CSV
  - XLSX
