IDs:
  controls:
    costs: costcomparisonCosts
    interventions: costcomparisonInterventions
    analyses: costcomparisonAnalyses
    colorblind: costcomparisonColorblind
  downloads:
    png: costcomparisonPNG
    pdf: costcomparisonPDF
    pptx: costcomparisonPPTX
    csv: costcomparisonCSV
    xlsx: costcomparisonXLSX
  panels:
    control: costcomparisonControlPanel
    visualization: costcomparisonVisualizationPanel
  title: costcomparisonTitle
  subtitle: costcomparisonSubtitle
  plot: costcomparisonPlot
costs:
  heading: Costs
  values:
    - ltbi_tests_000s
    - ltbi_txinits_000s
    - ltbi_txcomps_000s
    - tb_txinits_000s 
    - tb_txcomps_000s
  labels:
    ltbi_tests_000s: Total Cost
    ltbi_txtests_000s: LTBI Treatment Cost
    ltbi_txcomps_000s: TB Disease Treatment Cost
    tb_txinits_000s: Productivty Loss due to TB Treatment
    tb_txcomps_000s: Productivty Loss due to TB Death
  formatted:
    ltbi_tests_000s: |-
      Total Cost
      (in US Dollars)
    ltbi_txtests_000s: |-
     LTBI Treatment Cost 
     (in US Dollars)
    ltbi_txcomps_000s: |-
      TB Disease Treatment Cost 
      (in US Dollars)
    tb_txinits_000s: |-
       Productivty Loss due to TB Disease treatment
       (in US Dollars)
    tb_txcomps_000s: |-
       Productivty Loss due to TB Disease death
       (in US Dollars)
  descriptions:
       ltbi_tests_000s: Total Cost over selected time interval
       ltbi_txtests_000s: Total Cost of LTBI treatment over the selected time interval
       ltbi_txcomps_000s: Total Cost of TB Disease treatment over the selected time interval
       tb_txinits_000s: Productivty Loss due to TB Disease treatment over the selected time interval
       tb_txcomps_000s: Productivty Loss due to TB Disease death over the selected time interval
  selected:
  - yes
  - no
  - no
  - no
  - no
interventions:
  heading: Modeled Scenarios
  values:
  - intervention_1
  - intervention_2
  - intervention_3
  - intervention_4
  - intervention_5
  labels:
    intervention_1: LTBI treatment for new migrants
    intervention_2: Improved LTBI treatment in the US
    intervention_3: Enhanced case detection
    intervention_4: Enhanced TB treatment
    intervention_5: All improvements
  descriptions:
    intervention_1: Provision of LTBI testing and treatment for all new legal
      immigrants entering the US
    intervention_2: Intensification of the current LTBI targeted testing and
      treatment policy for high-risk populations, doubling treatment uptake within
      each risk group compared to current levels, and increasing the fraction cured
      among individuals initiating LTBI treatment, via a 3-month Isoniazid-Rifapentine
      drug regimen
    intervention_3: Improved detection of TB cases, such that the duration
      of untreated disease (time from TB incidence to the initiation of
      treatment) is reduced by 50%
    intervention_4: Improved treatment quality for TB, such that treatment default,
      failure rates, and the fraction of individuals receiving an incorrect drug
      regimen are reduced by 50% from current levels
    intervention_5: The combination of all intervention scenarios described above
analyses:
  heading: Sensitivity Analyses
  values:
  - scenario_1
  - scenario_2
  - scenario_3
  - scenario_5
  - scenario_6
  - scenario_7
  labels:
    scenario_1: No Transmission Within the US After 2020
    scenario_2: No TB or LTBI in New Migrants After 2020
    scenario_3: Reduced TB Prevention Effort
    scenario_5: Future Immigration at 2020 Levels
    scenario_6: Improving Global TB Control
    scenario_7: Rising Reactivation Risks
  formatted: # the |- allows newlines
    scenario_1: |-
      No transmission within
      the US after 2020
    scenario_2: |-
      No TB or LTBI in new
      migrants after 2020
    scenario_3: |-
      Reduced TB prevention
      effort
    scenario_4: |-
      Rising MDR-TB in
      new migrants
    scenario_5: |-
      Future immigration at
      2020 levels
    scenario_6: |-
      Improving global TB
      control
    scenario_7: |-
      Rising reactivation
      risk
  descriptions:
    scenario_1: From 2020 onwards, no individuals acquire M. TB infection from transmission within
      the United States. In this scenario the only source of new LTBI cases is from
      existing infection in new immigrants.
    scenario_2: From 2020 onwards, all individuals immigrating to the United States are free of
      M. TB infection, while maintaining the same total volume of immigration.
downloads:
  heading: Download
  labels:
  - PNG
  - PDF
  - PPTX
  - CSV
  - XLSX
